### ISSUE TITLE
Can't find variable: vtcc

### ISSUE THREAD

**Issue by JimTheMan** [founddrama/vt-code-camp-2012#2]
Hi. For some reason my karma / jasmine is not seeing the variables from my js files. How do you "import" variables and methods from your regular code inot the files with unit tests?

**Comment by founddrama** [comment]
Is your problem with the example code? or with something specific that you've written? Because at the time that I put this presentation together (whoa! has it been 4 years already?) I don't believe that I was using Karma. If you _are_ using Karma, you may want to check your assumptions about how your JS code is getting loaded into the runner. Are your JS files looking for variable that are otherwise declared on the page? If you've got coupling between your module's source code and other sources, look at how you can decouple them, or else mock out the expectations that the source has.

If you're looking for info about Karma, I wouldn't look here (as this repo never used it) -- instead look at [phantomjs-cookbook](https://github.com/founddrama/phantomjs-cookbook), which is the source code that accompanies my book (_PhantomJS Cookbook_) where I _do_ discuss using Karma.
